app = ""
primary_region = "sea"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "custom.Dockerfile"

[env]
  PORT = "4000"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
