name: Fly Deploy - Custom Site
on:
   push:
      branches:
         - main

concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true

jobs:
   deploy:
      name: Deploy custom app
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3
         - uses: superfly/flyctl-actions/setup-flyctl@master
         - run: flyctl deploy --app "$APP_NAME"-db --config ./fly.custom.toml --remote-only
           env:
              FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
              APP_NAME: ${{ secrets.APP_NAME }}
